import Head from 'next/head'
import DefaultLayout from "../layouts/DefaultLayout";
import MyMain from "../components/MyMain";
import HomeLayout from "../layouts/HomeLayout";
import CardList from "../components/CardsList";

export default function Home({posts}) {
    return (
        <div>
            <Head>
                <title>Rafl Media</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../public/favicon.ico" />
            </Head>
            <DefaultLayout>
                <MyMain>
                    <HomeLayout>
                        <CardList posts={posts}/>
                    </HomeLayout>
                </MyMain>
            </DefaultLayout>
        </div>
    )
}

export async function getServerSideProps(context) {
    const posts = await fetch(`http://localhost:3000/api/posts/category/${context.params.category}`).then(r => r.json())
    return {
        props: {posts}, // will be passed to the page component as props
    }
}