import Head from 'next/head'
import DefaultLayout from "../layouts/DefaultLayout";
import MyMain from "../components/MyMain";
import HomeLayout from "../layouts/HomeLayout";
import CardList from "../components/CardsList";

export default function Home() {



    return (
    <div>
      <Head>
        <title>Rafl Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rafl-media-backend/сlient/public/favicon.ico" />
      </Head>
            <DefaultLayout>
                <MyMain>
                    <HomeLayout>
                        <CardList/>
                    </HomeLayout>
                </MyMain>
            </DefaultLayout>
    </div>
  )
}
